### ISSUE TITLE
functionalProfileCategory renamed to Metering in SGrSpecifications

### ISSUE THREAD

**Issue by marco92** [SmartGridready/SGrPython#10]
SubMeterElectricity for example has been renamed to Metering:

https://github.com/SmartGridready/SGrSpecifications/blame/master/XMLInstances/FuncProfiles/FP_SGr_Metering_ActivePowerAC_m_1.0.xml

xsd_files have to be adopted accordingly

**Comment by mkrebs81** [comment]
This has already been fixed and only concerns specifications repository
