### ISSUE TITLE
OpenCEM updated

### ISSUE THREAD

**Issue by DavidZoggFHNW** [SmartGridready/SGrPython#14]
The branch OpenCEM has been updated by the changes in the sgr_library of the master branch.
It has been tested in simulated mode without any error.

Thus a merge of the OpenCEM branch to the main branch is possible.
Alternatively it is recommended to create a new repository SGrPythonSamples and move OpenCEM there.
This would be the same architecture as Java already has.

**Comment by mkrebs81** [comment]
I assume this has been moved to https://github.com/SmartGridready/SGrPythonSamples a long time ago...
