### ISSUE TITLE
async function (getval) should be syncfunction

### ISSUE THREAD

**Issue by joahlenzo** [SmartgridReady/SGrPython#4]
No need for async --> correct code needed for SGr-Intermediary below

def getval(self, fp_name, dp_name):
    dp = find_dp(self.root, fp_name, dp_name)
    request_path = dp.rest_apidata_point[0].rest_service_call.request_path
    url = 'https://' + str(self.base_url) + str(request_path)
    query = str(dp.rest_apidata_point[0].rest_service_call.response_query.query)

    headers = {header_entry.header_name: header_entry.value for header_entry in
               dp.rest_apidata_point[0].rest_service_call.request_header.header}
    headers['Authorization'] = 'Bearer ' + self.token

    res = requests.get(url=url, headers=headers)
    print(f"GETVAL: {res.status_code}")
    response = res.json()
    response = json.dumps(response)
    value = jmespath.search(query, json.loads(response))
    return value

**Comment by marco92** [comment]
Solved by using FastAPI library instead of Flask in the Intermediary library
