### ISSUE TITLE
Less restrictive dependencies

### ISSUE THREAD

**Issue by robin-schoch** [SmartGridready/SGrPython#5]
The requirements file force a specific version of each installed library. It would probably make sense to be less restrictive as this make it pretty hard to use this library with newer python version. For example support for numpy 1.20 has already ended 9 month ago and it only supports python version 3.7-3.9. Additionally SGrPython uses just floor, ceil and rint which is also present in newer releases (furthermore numpy might no be used at all as the required functionalities are provided by the standard lib and the math module).

**Comment by Zupeuc** [comment]
Thank you for your feedback Robin. I agree that it is wise to loosen the version constraints for improved compatibility.
